version = 1

[[files]]
template = "readme.jet"
fullname = "README.md"
vars = { appName = "My Project" }

[[files]]
template = "env.jet"
fullname = ".env"
vars = { appName = "My Project", appKey = "key123", appPort = 3000 }
