version = 1

[[data]]

[[data.readme]]
template = "readme.jet"
fullname = "README.md"
vars = { appName = "My Project" }

[[data.env]]
template = "env.jet"
fullname = ".env"
vars = { appName = "My Project", appKey = "key123", appPort = 3000 }
